package packreview

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/torjan0/cirewind/internal/model"
	"github.com/torjan0/cirewind/internal/packfixtures"
)

const reviewdogUnit = "review-packets/CIR-REVIEWDOG-ACTION-SETUP-2025/1.0.0"

// copyReviewdogAuthoredInputs copies only the hand-authored candidate files
// and the archived source object into a fresh unit; every derived file is
// regenerated by the assembler under test.
func copyReviewdogAuthoredInputs(t *testing.T, root string) string {
	t.Helper()
	source := filepath.Join("..", "..", reviewdogUnit, "candidate-content")
	unit := filepath.Join(root, reviewdogUnit)
	candidate := filepath.Join(unit, "candidate-content")
	mustMkdir(t, filepath.Join(candidate, "fixtures", "sources"))
	mustMkdir(t, filepath.Join(unit, "approvals"))
	for _, name := range []string{"pack.yaml", "sources.json", "claims.json", "conflicts.json"} {
		data, err := os.ReadFile(filepath.Join(source, name))
		if err != nil {
			t.Fatal(err)
		}
		mustWrite(t, filepath.Join(candidate, name), data)
	}
	archived, err := os.ReadFile(filepath.Join(source, "fixtures", "sources", "ghsa-database-record.json"))
	if err != nil {
		t.Fatal(err)
	}
	mustWrite(t, filepath.Join(candidate, "fixtures", "sources", "ghsa-database-record.json"), archived)
	for _, name := range []string{"pack-review-policy.json", "review-registry.json"} {
		data, err := os.ReadFile(filepath.Join("..", "..", name))
		if err != nil {
			t.Fatal(err)
		}
		mustWrite(t, filepath.Join(root, name), data)
	}
	pack, err := os.ReadFile(filepath.Join(candidate, "pack.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	mustMkdir(t, filepath.Join(root, "incidents", "candidates", "CIR-REVIEWDOG-ACTION-SETUP-2025"))
	mustWrite(t, filepath.Join(root, "incidents", "candidates", "CIR-REVIEWDOG-ACTION-SETUP-2025", "1.0.0.yaml"), pack)
	return unit
}

func reviewdogScenarios(t *testing.T) []AuthoredScenario {
	t.Helper()
	generated, err := packfixtures.Generate(context.Background(), "CIR-REVIEWDOG-ACTION-SETUP-2025", "1.0.0")
	if err != nil {
		t.Fatal(err)
	}
	scenarios := make([]AuthoredScenario, 0, len(generated))
	for _, scenario := range generated {
		forbidden := make([]ForbiddenExpectedFinding, 0, len(scenario.Forbidden))
		for _, state := range scenario.Forbidden {
			forbidden = append(forbidden, ForbiddenStateFor(scenario.ID, state.State, state.Rationale))
		}
		scenarios = append(scenarios, AuthoredScenario{ScenarioID: scenario.ID, Snapshot: scenario.Snapshot, AnalysisTime: scenario.AnalysisTime, Forbidden: forbidden})
	}
	return scenarios
}

func TestAssembleReviewdogCandidateIsDeterministicAndValidates(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	unit := copyReviewdogAuthoredInputs(t, root)
	input := AuthoringInput{
		CandidateContent: filepath.Join(unit, "candidate-content"), RepositoryPolicy: filepath.Join(root, "pack-review-policy.json"),
		Scenarios: reviewdogScenarios(t), ReviewPolicyProfile: "standard-v0.2",
		Preparation: Preparation{Preparer: HumanIdentity{Login: "synthetic-preparer", DatabaseID: 100}, Authors: []HumanIdentity{{Login: "synthetic-preparer", DatabaseID: 100}}, SourceTranscribers: []HumanIdentity{{Login: "synthetic-transcriber", DatabaseID: 101}}},
	}
	first, err := AssembleCandidate(ctx, input)
	if err != nil {
		t.Fatalf("assemble: %v", err)
	}
	manifest, err := os.ReadFile(filepath.Join(unit, "candidate-content", CandidateManifestName))
	if err != nil {
		t.Fatal(err)
	}
	second, err := AssembleCandidate(ctx, input)
	if err != nil {
		t.Fatal(err)
	}
	again, err := os.ReadFile(filepath.Join(unit, "candidate-content", CandidateManifestName))
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) || string(manifest) != string(again) {
		t.Fatal("assembly is not deterministic")
	}
	if first.IncidentID != "CIR-REVIEWDOG-ACTION-SETUP-2025" || first.PackVersion != "1.0.0" || len(first.ConflictIDs) != 2 {
		t.Fatalf("packet=%+v", first)
	}
	validated, err := ValidateUnit(ctx, unit, strings.Repeat("c", 40))
	if err != nil {
		t.Fatalf("assembled unit must validate: %v", err)
	}
	if validated.Pack.CanonicalPackSHA256 != first.CanonicalPackSHA256 {
		t.Fatal("validated unit does not bind the assembled pack")
	}
	expected, err := os.ReadFile(filepath.Join(unit, "candidate-content", "expected-findings.json"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(expected)
	for _, required := range []string{`"CONFIRMED_EXECUTED"`, `"CONFIRMED_DOWNLOADED"`, `"RUN_IN_WINDOW_MUTABLE_REF"`, `"POTENTIAL_TRANSITIVE"`, `"CONTRADICTORY_EVIDENCE"`, `"CURRENT_REFERENCE_ONLY"`, `"DECLARED_AT_RUN_SHA"`, `"UNKNOWN_EVIDENCE_GAP"`, "mutable-ref-last-minute", "mutable-ref-before-window"} {
		if !strings.Contains(text, required) {
			t.Fatalf("expected findings lack %s", required)
		}
	}
	for _, forbidden := range []string{"3f401fe1d58fe77e10d665ab713057375e39b887"} {
		if strings.Contains(text, forbidden) {
			t.Fatalf("expected findings name %s", forbidden)
		}
	}

	// A forbidden state that the derivation actually produces must abort
	// assembly rather than be recorded as an oracle.
	poisoned := reviewdogScenarios(t)
	for index := range poisoned {
		if poisoned[index].ScenarioID == "exact-execution-in-window" {
			poisoned[index].Forbidden = append(poisoned[index].Forbidden, ForbiddenStateFor(poisoned[index].ScenarioID, model.ConfirmedExecuted, "synthetic contradiction"))
		}
	}
	input.Scenarios = poisoned
	if _, err := AssembleCandidate(ctx, input); err == nil || !strings.Contains(err.Error(), "forbidden state") {
		t.Fatalf("forbidden derived state was not rejected: %v", err)
	}
	input.Scenarios = reviewdogScenarios(t)
	if _, err := AssembleCandidate(ctx, input); err != nil {
		t.Fatal(err)
	}

	// Editing a hand-authored ledger after assembly breaks the manifest.
	claims := filepath.Join(unit, "candidate-content", "claims.json")
	data, err := os.ReadFile(claims)
	if err != nil {
		t.Fatal(err)
	}
	mustWrite(t, claims, append(data, '\n'))
	if _, err := ValidateUnit(ctx, unit, strings.Repeat("c", 40)); err == nil {
		t.Fatal("post-assembly ledger edit validated")
	}
	if _, err := AssembleCandidate(ctx, AuthoringInput{CandidateContent: filepath.Join(unit, "missing"), RepositoryPolicy: input.RepositoryPolicy, Scenarios: input.Scenarios, ReviewPolicyProfile: "standard-v0.2", Preparation: input.Preparation}); err == nil {
		t.Fatal("missing candidate directory accepted")
	}
	if _, err := AssembleCandidate(ctx, AuthoringInput{CandidateContent: filepath.Join(unit, "candidate-content"), RepositoryPolicy: input.RepositoryPolicy, ReviewPolicyProfile: "standard-v0.2", Preparation: input.Preparation}); err == nil {
		t.Fatal("assembly without fixture scenarios accepted")
	}
}
