#!/bin/sh
# Regenerate or drift-check the staged README candidate under site/generated
# from a fresh demo case built at the current source revision.
#
# Usage: readme-candidate.sh VERSION [--check]

set -eu

usage='usage: readme-candidate.sh VERSION [--check]'
version=${1:?$usage}
mode=${2:-write}
case "$mode" in
  write|--check) ;;
  *)
    printf '%s\n' "$usage" >&2
    exit 2
    ;;
esac
case "$version" in
  v*|'')
    printf '%s\n' "version must be canonical SemVer without a v prefix: $version" >&2
    exit 2
    ;;
esac

root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
work_root=${CIREWIND_SITE_WORK_ROOT:-${TMPDIR:-/tmp}}
work_root=$(CDPATH='' cd -- "$work_root" && pwd)
work=$(mktemp -d "$work_root/cirewind-readme-candidate.XXXXXX")

case "$work" in
  "$work_root"/cirewind-readme-candidate.*) ;;
  *)
    printf '%s\n' "refusing unsafe README candidate workspace: $work" >&2
    exit 1
    ;;
esac

cleanup() {
  rm -rf -- "$work"
}
trap cleanup EXIT HUP INT TERM

mkdir -p "$work/tmp"
export TMPDIR="$work/tmp"
export GOTMPDIR="$work/tmp"

go_version=$(awk '/^go / { print $2; exit }' "$root/go.mod")
case "$go_version" in
  [0-9]*.[0-9]*.[0-9]*) ;;
  *)
    printf '%s\n' "invalid Go version in go.mod: $go_version" >&2
    exit 1
    ;;
esac
export GOTOOLCHAIN="go$go_version"
export GOFLAGS=-mod=readonly
export CGO_ENABLED=0

cd "$root"
mkdir -p site/generated
go build -trimpath -o "$work/cirewind" ./cmd/cirewind
go build -trimpath -o "$work/samplesite" ./tools/samplesite
"$work/cirewind" demo --out "$work/case" >/dev/null
"$work/cirewind" verify "$work/case" >/dev/null

if [ "$mode" = "--check" ]; then
  "$work/samplesite" readme --case "$work/case" --out-dir site/generated --version "$version" --check
  printf '%s\n' "README candidate under site/generated matches the regenerated bytes" >&2
else
  "$work/samplesite" readme --case "$work/case" --out-dir site/generated --version "$version"
  printf '%s\n' "README candidate regenerated under site/generated for v$version" >&2
fi
